new upstream relase

diff --git a/debian/lightdm.postinst b/debian/lightdm.postinst
--- a/debian/lightdm.postinst
+++ b/debian/lightdm.postinst
@@ -2,13 +2,6 @@
 
 set -e
 
-if dpkg-maintscript-helper supports mv_conffile; then
-  dpkg-maintscript-helper mv_conffile \
-    /etc/lightdm.conf \
-    /etc/lightdm/lightdm.conf \
-    0.3.7-0ubuntu2 -- "$@"
-fi    
-
 . /usr/share/debconf/confmodule
 
 THIS_PACKAGE=lightdm
@@ -28,78 +21,57 @@ if ! getent passwd lightdm >/dev/null; then
         usermod -s "/bin/false"            lightdm
 fi
 
-# Creating nopasswdlogin group if he isn't already there.
-# That enables the password-less login feature in the users-admin
-# tool of the gnome-system-tools for users that belong to it,
-# and which is working thanks to LightDM's PAM policy.
-if ! getent group nopasswdlogin >/dev/null; then
-        addgroup --system nopasswdlogin
-fi
-
-if [ -d /var/lib/lightdm ]; then
-  chown -R lightdm:lightdm /var/lib/lightdm || true
-  chmod 0750 /var/lib/lightdm
-fi
+mkdir -p /var/lib/lightdm
+chown -R lightdm:lightdm /var/lib/lightdm
+chmod 0750 /var/lib/lightdm
 
 # debconf is not a registry, so we only fiddle with the default file if it
 # does not exist
-if ! [ -e "$DEFAULT_DISPLAY_MANAGER_FILE" ]; then
-  DEFAULT_DISPLAY_MANAGER=
+if [ ! -e "$DEFAULT_DISPLAY_MANAGER_FILE" ]; then
   if db_get shared/default-x-display-manager; then
-    DEFAULT_DISPLAY_MANAGER="$RET"
-  fi
-  if [ -n "$DEFAULT_DISPLAY_MANAGER" ]; then
-    DAEMON_NAME=
-    if db_get "$DEFAULT_DISPLAY_MANAGER"/daemon_name; then
-      DAEMON_NAME="$RET"
+    # workaround debconf passthru bug (#379198)
+    if [ -z "$RET" ]; then
+      $RET="$THIS_PACKAGE"
     fi
-    if [ -z "$DAEMON_NAME" ]; then
-      # if we were unable to determine the name of the selected daemon (for
-      # instance, if the selected default display manager doesn't provide a
-      # daemon_name question), guess
-      DAEMON_NAME=$(which "$DEFAULT_DISPLAY_MANAGER" 2>/dev/null)
+    if [ "$THIS_PACKAGE" != "$RET" ]; then
+      echo "Please be sure to run \"dpkg --configure $RET\"."
     fi
-    if [ -n "$DAEMON_NAME" ]; then
-      echo "$DAEMON_NAME" > "$DEFAULT_DISPLAY_MANAGER_FILE"
+    if db_get "$RET"/daemon_name; then
+      echo "$RET" > $DEFAULT_DISPLAY_MANAGER_FILE
     fi
   fi
 fi
 
-# Registering the init scripts or starting the daemon may cause output to
-# stdout, which can confuse debconf.
-db_stop
+# remove the displaced old default display manager file if it exists
+if [ -e "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp" ]; then
+  rm "$DEFAULT_DISPLAY_MANAGER_FILE.dpkg-tmp"
+fi
 
-DEFAULT_SERVICE=/etc/systemd/system/display-manager.service
-# set default-display-manager systemd service link according to our config
-if [ "$1" = configure ] && [ -d /etc/systemd/system/ ]; then
-  if [ -e "$DEFAULT_DISPLAY_MANAGER_FILE" ]; then
+# debconf hangs if lightdm gets started below without this
+db_stop || true
+
+# update-rc.d levels
+S=30
+K=01
+
+if [ -x /etc/init.d/lightdm ]; then
+  update-rc.d lightdm defaults $S $K >/dev/null 2>&1
+fi
+
+if [ "$1" = "configure" ];
+then
+  invoke-rc.d dbus reload || true
+
+  # set default-display-manager systemd service link according to our config
+  if [ -e "$DEFAULT_DISPLAY_MANAGER_FILE" -a -d /etc/systemd/system/ ]; then
     SERVICE=/lib/systemd/system/$(basename $(cat "$DEFAULT_DISPLAY_MANAGER_FILE")).service
-    if [ -h "$DEFAULT_SERVICE" ] && [ $(readlink "$DEFAULT_SERVICE") = /dev/null ]; then
-      echo "Display manager service is masked" >&2
-    elif [ -e "$SERVICE" ]; then
-      ln -sf "$SERVICE" "$DEFAULT_SERVICE"
+    if [ -e "$SERVICE" ]; then
+      ln -sf "$SERVICE" /etc/systemd/system/display-manager.service
     else
-      echo "WARNING: $SERVICE is the selected default display manager but does not exist" >&2
-      rm -f "$DEFAULT_SERVICE"
+      echo "ERROR: $SERVICE is the selected default display manager but does not exist" >&2
     fi
-  else
-    rm -f "$DEFAULT_SERVICE"
   fi
 fi
-
-case "$1" in
-    configure)
-        # LP: #1189948
-        if dpkg --compare-versions "$2" lt "1.7.0-0ubuntu6" ; then
-            if [ -f /etc/apparmor.d/abstractions/lightdm ]; then
-                chmod 0644 /etc/apparmor.d/abstractions/lightdm || true
-            fi
-            if [ -f /etc/apparmor.d/abstractions/lightdm_chromium-browser ]; then
-                chmod 0644 /etc/apparmor.d/abstractions/lightdm_chromium-browser || true
-            fi
-        fi
-        ;;
-esac
 
 #DEBHELPER#
 
